env:
  global:
    - PACKAGE="xi-rope"
    - PINS="pvec:https://github.com/dbuenzli/pvec.git"
    - OPAM_VERSION=1.2.2
  matrix:
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
os:
  - linux
  - osx
language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
sudo: required
script: bash -ex .travis-opam.sh
branches:
  only:
    - gh-pages
    - /.*/
git:
  depth: 2
notifications:
  email: false
